- "catalog_name": "demo-lm3w-catalog01"
  "external_location_name": "demo-lm3w-external-location-001"
  "iam_role_name": "demo-lm3w-iam-role-001"
  "region": "ap-southeast-1"
  "s3_bucket_name": "demo-lm3w-uc-bucket-001"
  "storage_credential_name": "demo-lm3w-uc-credential-001"
- "catalog_name": "demo-lm3w-catalog02"
  "external_location_name": "demo-lm3w-external-location-002"
  "iam_role_name": "demo-lm3w-iam-role-002"
  "region": "ap-southeast-1"
  "s3_bucket_name": "demo-lm3w-uc-bucket-002"
  "storage_credential_name": "demo-lm3w-uc-credential-002"
- "catalog_name": "demo-lm3w-catalog03"
  "external_location_name": "demo-lm3w-external-location-003"
  "iam_role_name": "demo-lm3w-iam-role-003"
  "region": "ap-southeast-1"
  "s3_bucket_name": "demo-lm3w-uc-bucket-003"
  "storage_credential_name": "demo-lm3w-uc-credential-003"
